# Generated by Django 3.1 on 2020-08-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
